[package]
name = "etheroot"
version = "0.1.0"



[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
fp-evm = "2.0.0"
sp-core = { version = "34.0.0", features = ["rand"]}
wasm-pack = "0.13.0"
sp-externalities = "0.29.0"
serde_json = "1.0.125"
